//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAirEGMMAWBM
    {
        public int iAirEGMMAWBId { get; set; }
        public Nullable<int> iAirEGMFlightDetailsId { get; set; }
        public string sMAWBNo { get; set; }
        public string sPortOfOrigin { get; set; }
        public string sPortOfDestination { get; set; }
        public Nullable<decimal> dNoOfPackages { get; set; }
        public Nullable<decimal> dTotalWeight { get; set; }
        public string sGoodsDescription { get; set; }
        public string cShipmentType { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual tblAirEGMFlightDetailsM tblAirEGMFlightDetailsM { get; set; }
    }
}
