//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAirIGMFlightDetailsM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAirIGMFlightDetailsM()
        {
            this.tblAirIGMMAWBMs = new HashSet<tblAirIGMMAWBM>();
        }
    
        public int iFlightId { get; set; }
        public Nullable<int> iClientId { get; set; }
        public Nullable<int> iLocationId { get; set; }
        public string sFlightNo { get; set; }
        public Nullable<System.DateTime> dtDepartureDate { get; set; }
        public Nullable<System.DateTime> dtArrivalDate { get; set; }
        public Nullable<System.TimeSpan> tTime { get; set; }
        public string sPortOfOrigin { get; set; }
        public string sPortOfDestination { get; set; }
        public string sFlightRegistrationNo { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<bool> bIsReadyForTransmit { get; set; }
    
        public virtual tblAirClientMaster tblAirClientMaster { get; set; }
        public virtual tblAirLocationM tblAirLocationM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAirIGMMAWBM> tblAirIGMMAWBMs { get; set; }
    }
}
