//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAirClientMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAirClientMaster()
        {
            this.tblAirEGMFlightDetailsMs = new HashSet<tblAirEGMFlightDetailsM>();
            this.tblAirIGMFlightDetailsMs = new HashSet<tblAirIGMFlightDetailsM>();
            this.tblAirMAWBMs = new HashSet<tblAirMAWBM>();
        }
    
        public int iAirClientId { get; set; }
        public string sClientName { get; set; }
        public string sPassword { get; set; }
        public string sAddress { get; set; }
        public string sGSTNo { get; set; }
        public string sCARNNo { get; set; }
        public string sCompanyName { get; set; }
        public string sICEGateId { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public string sPinCode { get; set; }
        public string sEmailId { get; set; }
        public string sStateName { get; set; }
        public string sStateCode { get; set; }
        public string sClientCode { get; set; }
        public Nullable<decimal> dPricePerUnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAirEGMFlightDetailsM> tblAirEGMFlightDetailsMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAirIGMFlightDetailsM> tblAirIGMFlightDetailsMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAirMAWBM> tblAirMAWBMs { get; set; }
    }
}
