//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAirMAWBM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAirMAWBM()
        {
            this.tblAirHAWBMs = new HashSet<tblAirHAWBM>();
        }
    
        public long iMAWBId { get; set; }
        public Nullable<int> iAirClientId { get; set; }
        public Nullable<int> iLocationId { get; set; }
        public string sIGMNumber { get; set; }
        public Nullable<System.DateTime> dtIGMDate { get; set; }
        public string sFlightNumber { get; set; }
        public Nullable<System.DateTime> dtFlightDate { get; set; }
        public string sMAWBNo { get; set; }
        public string sOrigin { get; set; }
        public string sDestination { get; set; }
        public Nullable<decimal> nPackages { get; set; }
        public Nullable<decimal> nWeight { get; set; }
        public Nullable<byte> iStatus { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<System.DateTime> dtUpdateDate { get; set; }
        public Nullable<int> iUpdatedBy { get; set; }
    
        public virtual tblAirClientMaster tblAirClientMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAirHAWBM> tblAirHAWBMs { get; set; }
        public virtual tblAirLocationM tblAirLocationM { get; set; }
    }
}
