//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAirHAWBM
    {
        public long iHAWBId { get; set; }
        public Nullable<long> iMAWBId { get; set; }
        public string sHAWBNo { get; set; }
        public Nullable<decimal> nPackages { get; set; }
        public Nullable<decimal> nWeight { get; set; }
        public string sDescription { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public string sDestination { get; set; }
        public string sOrigin { get; set; }
    
        public virtual tblAirMAWBM tblAirMAWBM { get; set; }
    }
}
