//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAirLocationM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAirLocationM()
        {
            this.tblAirEGMFlightDetailsMs = new HashSet<tblAirEGMFlightDetailsM>();
            this.tblAirIGMFlightDetailsMs = new HashSet<tblAirIGMFlightDetailsM>();
            this.tblAirMAWBMs = new HashSet<tblAirMAWBM>();
        }
    
        public int iLocationId { get; set; }
        public string sCustomLocation { get; set; }
        public string sCustomCode { get; set; }
        public string sThreeLetterCode { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAirEGMFlightDetailsM> tblAirEGMFlightDetailsMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAirIGMFlightDetailsM> tblAirIGMFlightDetailsMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAirMAWBM> tblAirMAWBMs { get; set; }
    }
}
