//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBondMasterM
    {
        public int iBondId { get; set; }
        public string sCargoMovement { get; set; }
        public Nullable<int> iShippingId { get; set; }
        public Nullable<int> iPODId { get; set; }
        public Nullable<int> iFPODId { get; set; }
        public Nullable<decimal> nBondNo { get; set; }
        public string sCarrierCode { get; set; }
        public string sMLOCode { get; set; }
        public string sModeOfTransport { get; set; }
        public string sCFSName { get; set; }
        public string sCFSCode { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    
        public virtual tblPODMaster tblPODMaster { get; set; }
        public virtual tblPOFDMaster tblPOFDMaster { get; set; }
        public virtual tblShippingLine tblShippingLine { get; set; }
    }
}
