//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillingItem
    {
        public long iBillingId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> iClientId { get; set; }
        public Nullable<int> iMasterID { get; set; }
        public Nullable<int> iHouseNo { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iClientType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblInvoice tblInvoice { get; set; }
    }
}
