//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientMultipleEmail
    {
        public int iMailId { get; set; }
        public Nullable<int> iClientType { get; set; }
        public Nullable<int> iClientId { get; set; }
        public string sEmailId { get; set; }
        public string sEmailPersonName { get; set; }
        public Nullable<bool> bIsDefault { get; set; }
        public Nullable<bool> blsActive { get; set; }
    }
}
