//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientManagementFollowup
    {
        public int iClientManagementFollowupId { get; set; }
        public Nullable<int> iClientManagementId { get; set; }
        public string sFollowUpType { get; set; }
        public string sDifference { get; set; }
        public string sRemark { get; set; }
        public string sManagementRemark { get; set; }
        public Nullable<decimal> dRateOffered { get; set; }
        public Nullable<decimal> dFinalRate { get; set; }
        public Nullable<decimal> dRevenueExpected { get; set; }
        public Nullable<decimal> dActualRevenue { get; set; }
        public Nullable<System.DateTime> dtNextFollowUpDate { get; set; }
        public Nullable<bool> blsActive { get; set; }
        public Nullable<int> iAddedBy { get; set; }
        public Nullable<System.DateTime> dtAddedOn { get; set; }
        public string sAddedFromIp { get; set; }
        public Nullable<int> iModifiedBy { get; set; }
        public Nullable<System.DateTime> dtModifiedOn { get; set; }
        public string sModifiedFromIp { get; set; }
    }
}
