//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientManagement
    {
        public int iClientManagementId { get; set; }
        public string sClientCode { get; set; }
        public Nullable<System.DateTime> dtDate { get; set; }
        public string sNewClientName { get; set; }
        public string sExistingClientName { get; set; }
        public string sContactPersonName { get; set; }
        public string sContactPersonContactNo { get; set; }
        public string sDecisionMakerName { get; set; }
        public string sDecisionMakerContactNo { get; set; }
        public string sReference { get; set; }
        public string sBranch { get; set; }
        public string sAddress { get; set; }
        public Nullable<System.DateTime> dtNextFollowUpDate { get; set; }
        public string sEmailId { get; set; }
        public string sServiceType { get; set; }
        public Nullable<decimal> dRateOffered { get; set; }
        public Nullable<decimal> dFinalRate { get; set; }
        public Nullable<decimal> dRevenueExpected { get; set; }
        public Nullable<decimal> dActualRevenue { get; set; }
        public Nullable<System.DateTime> dtBusinessStartDate { get; set; }
        public string sAgreementImageName { get; set; }
        public Nullable<bool> blsActive { get; set; }
        public Nullable<int> iAddedBy { get; set; }
        public Nullable<System.DateTime> dtAddedOn { get; set; }
        public string sAddedFromIp { get; set; }
        public Nullable<int> iModifiedBy { get; set; }
        public Nullable<System.DateTime> dtModifiedOn { get; set; }
        public string sModifiedFromIp { get; set; }
    }
}
