//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClientMaster()
        {
            this.tblSeaSchedulings = new HashSet<tblSeaScheduling>();
        }
    
        public int iClientID { get; set; }
        public string sClientName { get; set; }
        public string sClientCode { get; set; }
        public string sCARN { get; set; }
        public string sOfficeAddress { get; set; }
        public string sCompanyName { get; set; }
        public string sLandLineNumber { get; set; }
        public string sMobileNumber { get; set; }
        public string sFaxNumber { get; set; }
        public string sEmailID { get; set; }
        public string sICEGateSeaID { get; set; }
        public string sICEGateSeaPassword { get; set; }
        public string sICEGateAirID { get; set; }
        public string sICEGateAirPassword { get; set; }
        public Nullable<bool> bIsActive { get; set; }
        public Nullable<System.DateTime> dtCreatedDate { get; set; }
        public Nullable<int> iCreatedBy { get; set; }
        public Nullable<System.DateTime> dtModifiedDate { get; set; }
        public Nullable<int> iModifiedBy { get; set; }
        public string sPinCode { get; set; }
        public string sGSTNNo { get; set; }
        public string sStateName { get; set; }
        public string sStateCode { get; set; }
        public Nullable<decimal> dPricePerUnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSeaScheduling> tblSeaSchedulings { get; set; }
    }
}
