//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        public int iCompanyId { get; set; }
        public string sName { get; set; }
        public string sAddress { get; set; }
        public string sPincode { get; set; }
        public string sCity { get; set; }
        public string sState { get; set; }
        public string sStateCode { get; set; }
        public string sPanNo { get; set; }
        public string sGSTNNo { get; set; }
        public string sContactNo { get; set; }
        public string sEamilID { get; set; }
        public Nullable<bool> blsIsDefault { get; set; }
        public Nullable<System.DateTime> dtCreateDate { get; set; }
        public Nullable<bool> blsActive { get; set; }
    }
}
