//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountryM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCountryM()
        {
            this.tblStateMs = new HashSet<tblStateM>();
        }
    
        public int iCountryId { get; set; }
        public string sCountryName { get; set; }
        public string sCountryCode { get; set; }
        public string sCountryPhoneCode { get; set; }
        public string sCurrencyCode { get; set; }
        public string sCountryDescription { get; set; }
        public string sCurrencyDescription { get; set; }
        public string sCountryImageUrl { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStateM> tblStateMs { get; set; }
    }
}
