//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoicePayment
    {
        public int iInvoicePaymentID { get; set; }
        public int iInvoiceId { get; set; }
        public Nullable<System.DateTime> dtCreateDate { get; set; }
        public Nullable<decimal> dAmount { get; set; }
        public Nullable<decimal> dTds { get; set; }
        public Nullable<decimal> dBalance { get; set; }
        public Nullable<bool> blsPaymentStatus { get; set; }
        public string sPaymentMode { get; set; }
        public string sCheckNeftNo { get; set; }
        public Nullable<System.DateTime> dtCheckDate { get; set; }
        public Nullable<System.DateTime> dtReceivedDate { get; set; }
        public Nullable<bool> blsActive { get; set; }
        public Nullable<int> iAddedBy { get; set; }
        public Nullable<System.DateTime> dtAddedOn { get; set; }
        public string sAddedFromIp { get; set; }
        public Nullable<int> iModifiedBy { get; set; }
        public Nullable<System.DateTime> dtModifiedOn { get; set; }
        public string sModifiedFromIp { get; set; }
    }
}
