//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceItem
    {
        public int iInvoiceItemID { get; set; }
        public int iInvoiceID { get; set; }
        public string sHSN_SAC { get; set; }
        public string sHSN_Desc { get; set; }
        public string sItemDescription { get; set; }
        public Nullable<int> iQuantity { get; set; }
        public string sUnit { get; set; }
        public Nullable<decimal> dAmountPerUnit { get; set; }
        public Nullable<decimal> dTotalAmount { get; set; }
        public Nullable<decimal> dCgstInPercent { get; set; }
        public Nullable<decimal> dSgstInPercent { get; set; }
        public Nullable<decimal> dIgstInPercent { get; set; }
        public Nullable<decimal> dCsesInPercent { get; set; }
        public Nullable<decimal> dCgstInAmount { get; set; }
        public Nullable<decimal> dSgstInAmount { get; set; }
        public Nullable<decimal> dIgstInAmount { get; set; }
        public Nullable<decimal> dCsesInAmount { get; set; }
        public Nullable<bool> blsActive { get; set; }
        public Nullable<int> iAddedBy { get; set; }
        public Nullable<System.DateTime> dtAddedOn { get; set; }
        public Nullable<int> iModifiedBy { get; set; }
        public Nullable<System.DateTime> dtModifiedOn { get; set; }
    
        public virtual tblInvoice tblInvoice { get; set; }
    }
}
