//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInvoice()
        {
            this.tblBillingItems = new HashSet<tblBillingItem>();
            this.tblInvoiceItems = new HashSet<tblInvoiceItem>();
        }
    
        public int iInvoiceID { get; set; }
        public string sInvoiceNo { get; set; }
        public Nullable<int> iClientId { get; set; }
        public Nullable<int> iYear { get; set; }
        public Nullable<int> iMonth { get; set; }
        public Nullable<System.DateTime> FromInvoiceDate { get; set; }
        public Nullable<System.DateTime> ToInvoiceDate { get; set; }
        public Nullable<System.DateTime> InvoiceCreatedDate { get; set; }
        public Nullable<short> iClientType { get; set; }
        public string sPOS { get; set; }
        public Nullable<int> iTotalQuantity { get; set; }
        public Nullable<decimal> dTotalAmount { get; set; }
        public Nullable<decimal> dTotalCgst { get; set; }
        public Nullable<decimal> dTotalSgst { get; set; }
        public Nullable<decimal> dTotalIgst { get; set; }
        public Nullable<decimal> dTotalCses { get; set; }
        public Nullable<decimal> dPaidAmount { get; set; }
        public Nullable<decimal> dBalance { get; set; }
        public Nullable<bool> blsActive { get; set; }
        public Nullable<int> iAddedBy { get; set; }
        public Nullable<System.DateTime> dtAddedOn { get; set; }
        public string sAddedFromIp { get; set; }
        public Nullable<int> iModifiedBy { get; set; }
        public Nullable<System.DateTime> dtModifiedOn { get; set; }
        public string sModifiedFromIp { get; set; }
        public Nullable<bool> blsPaymentStatus { get; set; }
        public string sPaymentMode { get; set; }
        public Nullable<System.DateTime> dtPaymentDate { get; set; }
        public Nullable<System.DateTime> dtReceivedDate { get; set; }
        public Nullable<int> iCompanyId { get; set; }
        public Nullable<decimal> dTotalTds { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBillingItem> tblBillingItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInvoiceItem> tblInvoiceItems { get; set; }
    }
}
