//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermissionsM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPermissionsM()
        {
            this.tblRolePermissionMaps = new HashSet<tblRolePermissionMap>();
        }
    
        public int iPermissionId { get; set; }
        public Nullable<int> iParentId { get; set; }
        public string sPermissionName { get; set; }
        public string sDescription { get; set; }
        public string sPath { get; set; }
        public Nullable<short> iSort { get; set; }
        public Nullable<bool> bShownInMenu { get; set; }
        public Nullable<bool> bIsMaster { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRolePermissionMap> tblRolePermissionMaps { get; set; }
    }
}
