//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRolePermissionMap
    {
        public int iPermissionRoleMapId { get; set; }
        public Nullable<int> iRoleId { get; set; }
        public Nullable<int> iPermissionId { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    
        public virtual tblPermissionsM tblPermissionsM { get; set; }
        public virtual tblRoleM tblRoleM { get; set; }
    }
}
