//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStateM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStateM()
        {
            this.tblCityMs = new HashSet<tblCityM>();
        }
    
        public int iStateId { get; set; }
        public int iCountryId { get; set; }
        public string sStateName { get; set; }
        public string sStateCode { get; set; }
        public string sDescription { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCityM> tblCityMs { get; set; }
        public virtual tblCountryM tblCountryM { get; set; }
    }
}
