//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSeaHBLMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSeaHBLMaster()
        {
            this.tblSeaContainerMasters = new HashSet<tblSeaContainerMaster>();
        }
    
        public int iHBLID { get; set; }
        public int iMBLId { get; set; }
        public Nullable<int> iSchedulingId { get; set; }
        public string sHouseBillofLadingNo { get; set; }
        public Nullable<System.DateTime> dtHouseBillofLadingDate { get; set; }
        public string sImporterName { get; set; }
        public string sImporterAddress1 { get; set; }
        public string sImporterAddress2 { get; set; }
        public string sImporterAddress3 { get; set; }
        public Nullable<decimal> dTotalNumberofPackages { get; set; }
        public string sPackageCode { get; set; }
        public Nullable<decimal> dGrossWeight { get; set; }
        public string sUnitofWeight { get; set; }
        public string sMarksandNumbers { get; set; }
        public string sGoodsDescription { get; set; }
        public Nullable<int> iAddedBy { get; set; }
        public Nullable<System.DateTime> dtAddedOn { get; set; }
        public string sAddedFromIp { get; set; }
        public Nullable<int> iModifiedBy { get; set; }
        public Nullable<System.DateTime> dtModifiedOn { get; set; }
        public string sModifiedFromIp { get; set; }
        public Nullable<byte> iSubLineNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSeaContainerMaster> tblSeaContainerMasters { get; set; }
        public virtual tblSeaMBLMaster tblSeaMBLMaster { get; set; }
        public virtual tblSeaScheduling tblSeaScheduling { get; set; }
    }
}
