//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSeaBondMaster
    {
        public int iBondID { get; set; }
        public int iSchedulingId { get; set; }
        public Nullable<decimal> dBondNumber { get; set; }
        public string sCarrierCode { get; set; }
        public string sMovementType { get; set; }
        public Nullable<int> iAddedBy { get; set; }
        public Nullable<System.DateTime> dtAddedOn { get; set; }
        public string sAddedFromIp { get; set; }
        public Nullable<int> iModifiedBy { get; set; }
        public Nullable<System.DateTime> dtModifiedOn { get; set; }
        public string sModifiedFromIp { get; set; }
    
        public virtual tblSeaScheduling tblSeaScheduling { get; set; }
    }
}
