//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSeaMBLMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSeaMBLMaster()
        {
            this.tblSeaHBLMasters = new HashSet<tblSeaHBLMaster>();
        }
    
        public int iMBLId { get; set; }
        public Nullable<int> iSchedulingId { get; set; }
        public Nullable<System.DateTime> dtMBLDate { get; set; }
        public Nullable<int> iPOSId { get; set; }
        public string sCargoMovement { get; set; }
        public string sCFSCode { get; set; }
        public Nullable<decimal> nIGMNo { get; set; }
        public Nullable<System.DateTime> dtIGMDate { get; set; }
        public string sIMOCode { get; set; }
        public string sVesselCode { get; set; }
        public string sVoyageNo { get; set; }
        public Nullable<decimal> nLineNo { get; set; }
        public Nullable<int> iAddedBy { get; set; }
        public Nullable<System.DateTime> dtAddedOn { get; set; }
        public string sAddedFromIp { get; set; }
        public Nullable<int> iModifiedBy { get; set; }
        public Nullable<System.DateTime> dtModifiedOn { get; set; }
        public string sModifiedFromIp { get; set; }
    
        public virtual tblPOSMaster tblPOSMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSeaHBLMaster> tblSeaHBLMasters { get; set; }
        public virtual tblSeaScheduling tblSeaScheduling { get; set; }
    }
}
