//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSeaScheduling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSeaScheduling()
        {
            this.tblSeaBondMasters = new HashSet<tblSeaBondMaster>();
            this.tblSeaContainerMasters = new HashSet<tblSeaContainerMaster>();
            this.tblSeaHBLMasters = new HashSet<tblSeaHBLMaster>();
            this.tblSeaMBLMasters = new HashSet<tblSeaMBLMaster>();
        }
    
        public int iSchedulingId { get; set; }
        public Nullable<int> iClientId { get; set; }
        public Nullable<int> iShippingID { get; set; }
        public string sMBLNumber { get; set; }
        public string sContainerNumber { get; set; }
        public Nullable<int> iPortOfDestinationID { get; set; }
        public Nullable<int> iPortOfFinalDestinationID { get; set; }
        public string sVesselName { get; set; }
        public Nullable<System.DateTime> dtEstimatedDateOfArrival { get; set; }
        public Nullable<bool> bCheckListSent { get; set; }
        public Nullable<bool> bCheckListApproved { get; set; }
        public Nullable<short> iSAction { get; set; }
        public Nullable<System.DateTime> dtReceivedOn { get; set; }
        public string sRemarks { get; set; }
        public string sInvoiceRemarks { get; set; }
        public Nullable<int> iCreatedBy { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public string sAddedFromIp { get; set; }
        public Nullable<int> iModifiedBy { get; set; }
        public Nullable<System.DateTime> dtModifiedOn { get; set; }
        public string sModifiedFromIp { get; set; }
    
        public virtual tblClientMaster tblClientMaster { get; set; }
        public virtual tblPODMaster tblPODMaster { get; set; }
        public virtual tblPOFDMaster tblPOFDMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSeaBondMaster> tblSeaBondMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSeaContainerMaster> tblSeaContainerMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSeaHBLMaster> tblSeaHBLMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSeaMBLMaster> tblSeaMBLMasters { get; set; }
        public virtual tblShippingLine tblShippingLine { get; set; }
    }
}
