//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSeaContainerMaster
    {
        public int iContainerId { get; set; }
        public Nullable<int> iSchedulingId { get; set; }
        public Nullable<int> iHBLID { get; set; }
        public string sContainerNumber { get; set; }
        public string sContainerSealNo { get; set; }
        public Nullable<decimal> nTotalPackages { get; set; }
        public Nullable<decimal> nContainerWeight { get; set; }
        public string sContainerStatus { get; set; }
        public string sISOCode { get; set; }
        public Nullable<int> iAddedBy { get; set; }
        public Nullable<System.DateTime> dtAddedOn { get; set; }
        public string sAddedFromIp { get; set; }
        public Nullable<int> iModifiedBy { get; set; }
        public Nullable<System.DateTime> dtModifiedOn { get; set; }
        public string iModifiedFromIp { get; set; }
        public Nullable<bool> bStatus { get; set; }
    
        public virtual tblSeaHBLMaster tblSeaHBLMaster { get; set; }
        public virtual tblSeaScheduling tblSeaScheduling { get; set; }
    }
}
