//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserM
    {
        public int iUserId { get; set; }
        public string sUsername { get; set; }
        public string sPassword { get; set; }
        public Nullable<int> iRoleId { get; set; }
        public string sFirstName { get; set; }
        public string sLastName { get; set; }
        public string sAddress { get; set; }
        public string sAddress2 { get; set; }
        public Nullable<int> iCityId { get; set; }
        public string sZipCode { get; set; }
        public string sEmailID { get; set; }
        public string sPhotoUrl { get; set; }
        public string sPhoneNo { get; set; }
        public Nullable<int> iActionBy { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public string sPANCARD { get; set; }
        public Nullable<int> iClientID { get; set; }
    
        public virtual tblCityM tblCityM { get; set; }
        public virtual tblRoleM tblRoleM { get; set; }
    }
}
