//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AirSea_MAW_MBL
    {
        public int ClientId { get; set; }
        public long MasterNoID { get; set; }
        public long HouseNoID { get; set; }
        public string ContainerStatus { get; set; }
        public string ClientName { get; set; }
        public string CustomLocation { get; set; }
        public string MasterNumber { get; set; }
        public string HouseNo { get; set; }
        public string ImporterName { get; set; }
        public string CustomCode { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public int ClientType { get; set; }
    }
}
