//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzollutionPro_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ClientMaster
    {
        public int iClientId { get; set; }
        public string ClientName { get; set; }
        public string iClientType { get; set; }
        public string sStateCode { get; set; }
        public string sClientCode { get; set; }
        public Nullable<decimal> dPricePerUnit { get; set; }
    }
}
